#include <stdio.h>
#include <string.h>
#include <stdlib.h>

struct Medicine {
    char name[50];
        float price;
            int day, month, year;
                int quantity;
                };

                struct Medicine med[100];
                int medCount = 0;

                void addMedicine() {
                    printf("Enter name: ");
                        scanf("%s", med[medCount].name);
                            printf("Enter price: ");
                                scanf("%f", &med[medCount].price);
                                    printf("Enter expiry date (dd mm yyyy): ");
                                        scanf("%d %d %d", &med[medCount].day, &med[medCount].month, &med[medCount].year);
                                            printf("Enter quantity: ");
                                                scanf("%d", &med[medCount].quantity);
                                                    medCount++;
                                                    }

                                                    void saveToFile() {
                                                        FILE *f = fopen("medicines.txt", "w");
                                                            for(int i=0;i<medCount;i++) {
                                                                    fprintf(f, "%s %f %d %d %d %d\n", med[i].name, med[i].price, med[i].day, med[i].month, med[i].year, med[i].quantity);
                                                                        }
                                                                            fclose(f);
                                                                            }

                                                                            void loadFromFile() {
                                                                                FILE *f = fopen("medicines.txt", "r");
                                                                                    medCount = 0;
                                                                                        while(fscanf(f, "%s %f %d %d %d %d", med[medCount].name, &med[medCount].price, &med[medCount].day, &med[medCount].month, &med[medCount].year, &med[medCount].quantity) != EOF) {
                                                                                                medCount++;
                                                                                                    }
                                                                                                        fclose(f);
                                                                                                        }

                                                                                                        void checkExpiry(int d, int m, int y) {
                                                                                                            printf("Expired Medicines:\n");
                                                                                                                for(int i=0;i<medCount;i++) {
                                                                                                                        if(med[i].year < y || (med[i].year==y && med[i].month<m) || (med[i].year==y && med[i].month==m && med[i].day<d)) {
                                                                                                                                    printf("%s\n", med[i].name);
                                                                                                                                            }
                                                                                                                                                }
                                                                                                                                                }

                                                                                                                                                void sortMedicinesByPrice() {
                                                                                                                                                    for(int i=0;i<medCount-1;i++) {
                                                                                                                                                            for(int j=i+1;j<medCount;j++) {
                                                                                                                                                                        if(med[i].price > med[j].price) {
                                                                                                                                                                                        struct Medicine temp = med[i];
                                                                                                                                                                                                        med[i] = med[j];
                                                                                                                                                                                                                        med[j] = temp;
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                void sellMedicine() {
                                                                                                                                                                                                                                                    char name[50];
                                                                                                                                                                                                                                                        int qty;
                                                                                                                                                                                                                                                            float total = 0;
                                                                                                                                                                                                                                                                while(1) {
                                                                                                                                                                                                                                                                        printf("Enter medicine name to sell (or 'done'): ");
                                                                                                                                                                                                                                                                                scanf("%s", name);
                                                                                                                                                                                                                                                                                        if(strcmp(name, "done")==0) break;
                                                                                                                                                                                                                                                                                                printf("Enter quantity: ");
                                                                                                                                                                                                                                                                                                        scanf("%d", &qty);
                                                                                                                                                                                                                                                                                                                int found = 0;
                                                                                                                                                                                                                                                                                                                        for(int i=0;i<medCount;i++) {
                                                                                                                                                                                                                                                                                                                                    if(strcmp(med[i].name, name)==0) {
                                                                                                                                                                                                                                                                                                                                                    if(med[i].quantity >= qty) {
                                                                                                                                                                                                                                                                                                                                                                        med[i].quantity -= qty;
                                                                                                                                                                                                                                                                                                                                                                                            total += med[i].price * qty;
                                                                                                                                                                                                                                                                                                                                                                                                                printf("Sold %d of %s\n", qty, name);
                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Not enough stock\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    found = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(!found) printf("Medicine not found\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Total Bill: %.2f\n", total);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        void displayMedicines() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for(int i=0;i<medCount;i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("%s %.2f %02d-%02d-%04d Qty:%d\n", med[i].name, med[i].price, med[i].day, med[i].month, med[i].year, med[i].quantity);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int main() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            loadFromFile();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int choice;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    while(1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("1.Add Medicine\n2.Sell Medicine\n3.Check Expiry\n4.Display Medicines\n5.Sort by Price\n6.Save & Exit\nChoose: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scanf("%d", &choice);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(choice==1) addMedicine();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else if(choice==2) sellMedicine();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else if(choice==3) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int d,m,y;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Enter current date (dd mm yyyy): ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                scanf("%d %d %d", &d,&m,&y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            checkExpiry(d,m,y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else if(choice==4) displayMedicines();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else if(choice==5) sortMedicinesByPrice();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else if(choice==6) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        saveToFile();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    